const APP_ORIGIN='https://bakurinha.github.io';
const APP_URL='https://bakurinha.github.io/minha-lista/';
const SHARE_TTL=60*60*24*7;
const MAX_ITEMS=2000,MAX_CATALOGS=2500,MAX_BODY_BYTES=900000;
const ID_RE=/^[A-Za-z0-9_-]{36}$/;
const CORS={'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400','Vary':'Origin'};
function headers(origin){return{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer',...CORS,'Access-Control-Allow-Origin':origin===APP_ORIGIN?APP_ORIGIN:''}}
function json(data,status=200,origin=''){const h=headers(origin);if(!h['Access-Control-Allow-Origin'])delete h['Access-Control-Allow-Origin'];return new Response(JSON.stringify(data),{status,headers:h})}
function allowed(origin){return origin===APP_ORIGIN}
function randomId(){const b=new Uint8Array(18);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function text(v,max){return typeof v==='string'&&v.length<=max?v:null}
function date(v){if(v===null||v===undefined||v==='')return null;if(typeof v!=='string'||!/^(?:\d{4})-(?:\d{2})-(?:\d{2})$/.test(v))return undefined;const [y,m,d]=v.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d?v:undefined}
function finite(v,max,positive=false){if(v===null||v===undefined||v==='')return true;if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max)return false;return !positive||v>0}
function catalog(c){if(!c||typeof c!=='object')return null;const id=text(c.id,100),name=text(c.name,120),ean=typeof c.ean==='string'?c.ean.replace(/\D/g,''):'';if(!id||!name||!name.trim()||ean.length>14)return null;return{id,name:name.trim(),brand:text(c.brand,120)||'',unit:text(c.unit,60)||'un',category:text(c.category,80)||'Outros',notes:text(c.notes,2000)||'',ean}}
function item(i){if(!i||typeof i!=='object'||!text(i.id,100)||!text(i.mainItemId,100)||typeof i.done!=='boolean'||!finite(i.quantity,1000000,true)||!finite(i.value,1000000000)||!finite(i.packageQuantity,1000000,true))return null;const d=date(i.date),e=date(i.expiryDate);if(d===undefined||e===undefined||typeof i.marketName!=='string'||typeof i.comments!=='string')return null;return{id:i.id,mainItemId:i.mainItemId,done:i.done,quantity:i.quantity??null,date:d,value:i.value??null,marketName:i.marketName.slice(0,160),comments:i.comments.slice(0,2000),productName:text(i.productName,120)||'',productBrand:text(i.productBrand,120)||'',productUnit:text(i.productUnit,60)||'un',productCategory:text(i.productCategory,80)||'Outros',packageQuantity:i.packageQuantity??null,packageUnit:text(i.packageUnit,60)||null,expiryDate:e}}
export function validatePayload(p){if(!p||typeof p!=='object'||p.app!=='Minha Lista de Supermercado'||!['shared-list-v2','shared-list-v3'].includes(p.format)||![2,3].includes(p.version))return{ok:false,error:'format'};const l=p.list;if(!l||typeof l!=='object'||!text(l.name,120)?.trim()||date(l.date)===undefined||!Array.isArray(p.catalogs)||p.catalogs.length>MAX_CATALOGS||!Array.isArray(l.items)||l.items.length>MAX_ITEMS)return{ok:false,error:'list'};const catalogs=p.catalogs.map(catalog);if(catalogs.some(x=>!x))return{ok:false,error:'catalog'};const ids=new Set(catalogs.map(x=>x.id));if(ids.size!==catalogs.length)return{ok:false,error:'duplicate-catalog'};const items=l.items.map(item);if(items.some(x=>!x||!ids.has(x.mainItemId)))return{ok:false,error:'item'};return{ok:true,value:{app:'Minha Lista de Supermercado',format:'shared-list-v3',version:3,list:{id:'',name:l.name.trim(),date:date(l.date),purchaseType:l.purchaseType==='virtual'?'virtual':'local',comments:text(l.comments,2000)||'',archived:false,items},catalogs}}}
async function body(request){const len=Number(request.headers.get('content-length')||0);if(len&&len>MAX_BODY_BYTES)throw Error('too-large');const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY_BYTES)throw Error('too-large');return JSON.parse(raw)}
async function create(request,env,origin){let p;try{p=await body(request)}catch(e){return json({error:e.message==='too-large'?'payload-too-large':'invalid-json'},400,origin)}const checked=validatePayload(p);if(!checked.ok)return json({error:'invalid-payload',field:checked.error},400,origin);const id=randomId();await env.SHARES.put(id,JSON.stringify(checked.value),{expirationTtl:SHARE_TTL});return json({id,url:`${new URL(request.url).origin}/s/${id}`,expiresIn:SHARE_TTL},201,origin)}
async function get(id,env,origin){if(!ID_RE.test(id))return json({error:'not-found'},404,origin);const value=await env.SHARES.get(id);if(!value)return json({error:'not-found'},404,origin);return new Response(value,{status:200,headers:{...headers(origin)}})}
async function redirect(id){const u=new URL(APP_URL);u.searchParams.set('shared',id);return new Response(null,{status:302,headers:{Location:u.toString(),'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'}})}
export async function handleRequest(request,env){const u=new URL(request.url),origin=request.headers.get('Origin')||'';if(!allowed(origin))return new Response('Forbidden',{status:403,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...CORS,'Access-Control-Allow-Origin':APP_ORIGIN}});if(u.pathname==='/api/share'&&request.method==='POST')return create(request,env,origin);if(u.pathname.startsWith('/api/share/')&&request.method==='GET')return get(u.pathname.slice('/api/share/'.length),env,origin);if(u.pathname.startsWith('/s/')&&request.method==='GET'){const id=u.pathname.slice(3);if(!ID_RE.test(id)||!(await env.SHARES.get(id)))return new Response('Compartilhamento não encontrado ou expirado.',{status:404,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});return redirect(id)}return json({service:'minha-lista-share',status:'ok'},200,origin)}
export default{fetch:handleRequest};
