const APP_ORIGIN='https://bakurinha.github.io';
const APP_URL='https://bakurinha.github.io/minha-lista/';
const SHARE_TTL=60*60*24*7;
const MAX_ITEMS=2000;
const MAX_CATALOGS=2500;
const MAX_BODY_BYTES=900000;
const ID_RE=/^[A-Za-z0-9_-]{36}$/;
const CORS_HEADERS={'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400','Vary':'Origin'};
function json(data,status=200,origin=''){const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer',...CORS_HEADERS};if(origin===APP_ORIGIN)headers['Access-Control-Allow-Origin']=APP_ORIGIN;return new Response(JSON.stringify(data),{status,headers})}
function allowedOrigin(origin){return !origin||origin===APP_ORIGIN}
function randomId(){const b=new Uint8Array(18);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function text(v,max){return typeof v==='string'&&v.length<=max?v:null}
function dateOrNull(v){if(v===null||v===undefined||v==='')return null;if(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)){const [y,m,d]=v.split('-').map(Number);const dt=new Date(Date.UTC(y,m-1,d));return dt.getUTCFullYear()===y&&dt.getUTCMonth()===m-1&&dt.getUTCDate()===d?v:null}return undefined}
function finite(v,max){return v===null||v===undefined||v===''||(typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max)}
function cleanCatalog(c){if(!c||typeof c!=='object')return null;const cid=text(c.id,200),name=text(c.name,120),ean=typeof c.ean==='string'?c.ean.replace(/\D/g,''):'';if(!cid||!name||!name.trim()||ean.length>14)return null;return{id:cid,name:name.trim(),brand:text(c.brand,120)||'',unit:text(c.unit,60)||'un',category:text(c.category,80)||'Outros',notes:text(c.notes,2000)||'',ean}}
function cleanItem(i){if(!i||typeof i!=='object')return null;const mainItemId=text(i.mainItemId,200),date=dateOrNull(i.date);if(!mainItemId||date===undefined||!finite(i.quantity,1000000)||!finite(i.value,1000000000))return null;return{id:text(i.id,200)||'',mainItemId,done:typeof i.done==='boolean'?i.done:Boolean(i.done),quantity:i.quantity??null,date,value:i.value??null,marketName:text(i.marketName,160)||'',comments:text(i.comments,2000)||'',productName:text(i.productName,120)||'',productBrand:text(i.productBrand,120)||'',productUnit:text(i.productUnit,60)||'un',productCategory:text(i.productCategory,80)||'Outros'}}
export function validatePayload(payload){if(!payload||typeof payload!=='object')return{ok:false,error:'payload'};if(payload.app!=='Minha Lista de Supermercado')return{ok:false,error:'app'};if(payload.format!=='shared-list-v2'||payload.version!==2)return{ok:false,error:'format'};const list=payload.list;if(!list||typeof list!=='object')return{ok:false,error:'list'};const name=text(list.name,120),listDate=dateOrNull(list.date);if(!name||!name.trim())return{ok:false,error:'list.name'};if(listDate===undefined)return{ok:false,error:'list.date'};if(!Array.isArray(payload.catalogs)||payload.catalogs.length>MAX_CATALOGS)return{ok:false,error:'catalogs'};if(!Array.isArray(list.items)||list.items.length>MAX_ITEMS)return{ok:false,error:'items'};const catalogs=payload.catalogs.map(cleanCatalog);if(catalogs.some(x=>!x))return{ok:false,error:'catalog.item'};const ids=new Set(catalogs.map(x=>x.id));if(ids.size!==catalogs.length)return{ok:false,error:'catalog.duplicate-id'};const items=list.items.map(cleanItem);if(items.some(x=>!x||!ids.has(x.mainItemId)))return{ok:false,error:'item.reference'};return{ok:true,value:{app:'Minha Lista de Supermercado',format:'shared-list-v2',version:2,list:{id:'',name:name.trim(),date:listDate,purchaseType:list.purchaseType==='virtual'?'virtual':'local',comments:text(list.comments,2000)||'',archived:false,items},catalogs}}}
async function readJson(request){const len=Number(request.headers.get('content-length')||0);if(len&&len>MAX_BODY_BYTES)throw Error('body-too-large');const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY_BYTES)throw Error('body-too-large');return JSON.parse(raw)}
async function createShare(request,env,origin){let payload;try{payload=await readJson(request)}catch(e){return json({error:e.message==='body-too-large'?'payload-too-large':'invalid-json'},400,origin)}const checked=validatePayload(payload);if(!checked.ok)return json({error:'invalid-payload',field:checked.error},400,origin);const id=randomId();await env.SHARES.put(id,JSON.stringify(checked.value),{expirationTtl:SHARE_TTL});return json({id,url:`${new URL(request.url).origin}/s/${id}`,expiresIn:SHARE_TTL},201,origin)}
async function getShare(id,env,origin){if(!ID_RE.test(id))return json({error:'not-found'},404,origin);const value=await env.SHARES.get(id);if(!value)return json({error:'not-found'},404,origin);return new Response(value,{status:200,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer',...CORS_HEADERS,...(origin===APP_ORIGIN?{'Access-Control-Allow-Origin':APP_ORIGIN}:{})}})}
function redirectShare(id){const u=new URL(APP_URL);u.searchParams.set('shared',id);return new Response(null,{status:302,headers:{Location:u.toString(),'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'}})}
export async function handleRequest(request,env){const u=new URL(request.url),origin=request.headers.get('Origin')||'';if(!allowedOrigin(origin))return new Response('Forbidden',{status:403,headers:{'X-Content-Type-Options':'nosniff'}});if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...CORS_HEADERS,...(origin===APP_ORIGIN?{'Access-Control-Allow-Origin':APP_ORIGIN}:{})}});if(u.pathname==='/api/share'&&request.method==='POST')return createShare(request,env,origin);if(u.pathname.startsWith('/api/share/')&&request.method==='GET')return getShare(u.pathname.slice('/api/share/'.length),env,origin);if(u.pathname.startsWith('/s/')&&request.method==='GET'){const id=u.pathname.slice(3);if(!ID_RE.test(id)||!(await env.SHARES.get(id)))return new Response('Compartilhamento não encontrado ou expirado.',{status:404,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});return redirectShare(id)}return json({service:'minha-lista-share',status:'ok'},200,origin)}
export default{fetch:handleRequest};
