(()=>{
'use strict';
const DB='MinhaListaDB',MAX=20*1024*1024;
const $=id=>document.getElementById(id);
const toast=m=>{const t=$('toast');if(t){t.textContent=m;t.classList.add('show');clearTimeout(t._v230);t._v230=setTimeout(()=>t.classList.remove('show'),2800)}else alert(m)};
const open=()=>new Promise((res,rej)=>{const r=indexedDB.open(DB);r.onerror=()=>rej(r.error||Error('IndexedDB indisponível'));r.onsuccess=()=>res(r.result)});
const all=(d,s)=>new Promise((res,rej)=>{const r=d.transaction(s,'readonly').objectStore(s).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error||Error('Falha IndexedDB'))});
const tx=(d,stores,fn)=>new Promise((res,rej)=>{let t;try{t=d.transaction(stores,'readwrite');fn(t)}catch(e){try{t?.abort()}catch{}rej(e);return}t.oncomplete=res;t.onerror=()=>rej(t.error||Error('Falha IndexedDB'));t.onabort=()=>rej(t.error||Error('Transação cancelada'))});
const validDate=v=>v==null||v===''||(/^\d{4}-\d{2}-\d{2}$/.test(String(v))&&(()=>{const [y,m,d]=String(v).split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d})());
const id=v=>typeof v==='string'&&v.length>=1&&v.length<=200;
const optionalNum=(v,max=1000000)=>v==null||v===''||(typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max);
const cleanSettings=s=>Object.fromEntries(Object.entries(s||{}).filter(([k])=>!['referenceDataVersion','referenceSeedV230'].includes(k)));
async function snapshot(){const d=await open();try{const stores=['catalogs','lists','history','wishlist','trash','settings','inventory'];const rows=await Promise.all(stores.map(s=>all(d,s)));const [catalogs,lists,history,wishlist,trash,settings,inventory]=rows;return{app:'Minha Lista de Supermercado',backupFormatVersion:2,schemaVersion:6,exportedAt:new Date().toISOString(),catalogs,lists,history,wishlist,trash,inventory,settings:cleanSettings(Object.fromEntries(settings.map(x=>[x.key,x.value])))}}finally{d.close()}}
function normalizeLegacyBackup(raw){if(!raw||raw.app!=='Minha Lista de Supermercado'||raw.backupFormatVersion===2)return raw;if(raw.version!=='2.2')return null;if(!Array.isArray(raw.catalogs)||!Array.isArray(raw.lists)||!Array.isArray(raw.history))return null;const d={app:'Minha Lista de Supermercado',backupFormatVersion:1,schemaVersion:Number.isInteger(raw.schemaVersion)?raw.schemaVersion:3,exportedAt:raw.exportedAt||new Date().toISOString(),catalogs:raw.catalogs,lists:raw.lists,history:raw.history,wishlist:Array.isArray(raw.wishlist)?raw.wishlist:[],trash:Array.isArray(raw.trash)?raw.trash:[],settings:raw.settings&&typeof raw.settings==='object'&&!Array.isArray(raw.settings)?raw.settings:{}};d.catalogs=d.catalogs.map(c=>({...c,brand:String(c.brand||''),unit:String(c.unit||'un'),category:String(c.category||'Outros'),notes:String(c.notes||'')}));d.lists=d.lists.map(l=>({...l,purchaseType:l.purchaseType==='virtual'?'virtual':'local',comments:String(l.comments||''),archived:!!l.archived,items:Array.isArray(l.items)?l.items.map(i=>({...i,quantity:i.quantity==null?null:i.quantity,value:i.value==null?null:i.value,date:i.date||null,marketName:String(i.marketName||''),comments:String(i.comments||'')})):[]}));d.history=d.history.map(h=>({...h,mainItemId:h.mainItemId||null,itemName:String(h.itemName||''),brand:String(h.brand||''),unit:String(h.unit||''),marketName:String(h.marketName||''),origin:String(h.origin||'legacy-backup')}));return d}
function validate(data){data=normalizeLegacyBackup(data);if(!data||data.app!=='Minha Lista de Supermercado')return 'Arquivo incompatível.';if(![1,2].includes(data.backupFormatVersion))return 'Versão de backup não suportada.';for(const k of ['catalogs','lists','history','wishlist','trash'])if(!Array.isArray(data[k]))return `Campo inválido: ${k}.`;if(!data.settings||typeof data.settings!=='object'||Array.isArray(data.settings))return 'Configurações inválidas.';if(data.backupFormatVersion===2&&!Array.isArray(data.inventory))return 'Estoque inválido.';if(JSON.stringify(data).length>MAX)return 'O backup excede 20 MB.';const cats=new Set();for(const c of data.catalogs){if(!c||!id(c.id)||typeof c.name!=='string'||!c.name.trim()||c.name.length>120)return 'Catálogo inválido.';if(cats.has(c.id))return 'Catálogo duplicado.';cats.add(c.id)}const allCats=cats;const lists=new Set();for(const l of data.lists){if(!l||!id(l.id)||typeof l.name!=='string'||!l.name.trim()||l.name.length>120||!Array.isArray(l.items)||!validDate(l.date))return 'Lista inválida.';if(lists.has(l.id))return 'Lista duplicada.';lists.add(l.id);for(const i of l.items){if(!i||!id(i.id)||!id(i.mainItemId)||!allCats.has(i.mainItemId)||typeof i.done!=='boolean'||!optionalNum(i.quantity)||!optionalNum(i.value,1000000000)||!validDate(i.date)||!validDate(i.expiryDate)||!optionalNum(i.packageQuantity)||typeof (i.marketName??'')!=='string'||typeof (i.comments??'')!=='string')return 'Item de lista inválido.'}}
for(const h of data.history)if(!h||!id(h.id)||h.mainItemId&&!allCats.has(h.mainItemId)||typeof h.itemName!=='string'||!optionalNum(h.value,1000000000)||!validDate(h.date))return 'Histórico inválido.';
for(const w of data.wishlist)if(!w||!id(w.id)||typeof w.name!=='string'||!w.name.trim())return 'Lista de desejos inválida.';
for(const t of data.trash)if(!t||!id(t.id)||!['catalog','list'].includes(t.type)||!t.data)return 'Lixeira inválida.';
if(data.backupFormatVersion===2)for(const x of data.inventory){if(!x||!id(x.id)||!id(x.mainItemId)||!allCats.has(x.mainItemId)||!optionalNum(x.quantity)||!validDate(x.expiryDate)||!validDate(x.entryDate)||!optionalNum(x.packageQuantity)||!optionalNum(x.minQuantity)||typeof (x.packageUnit??'')!=='string'||typeof (x.marketName??'')!=='string'||typeof (x.location??'')!=='string'||typeof (x.notes??'')!=='string')return 'Registro de estoque inválido'}return null}
const migrate=data=>{const normalized=normalizeLegacyBackup(data);if(normalized&&normalized.backupFormatVersion===2)return normalized;if(normalized&&normalized.backupFormatVersion===1)return {...normalized,backupFormatVersion:2,schemaVersion:6,inventory:[]};if(data?.backupFormatVersion===1)return {...data,backupFormatVersion:2,schemaVersion:6,inventory:Array.isArray(data.inventory)?data.inventory:[]};return data};
const download=(name,text)=>{const u=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)};
async function exportV2(){try{download(`minha-lista-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(await snapshot(),null,2));toast('Backup V2 exportado com estoque.')}catch(e){console.error(e);toast('Não foi possível exportar o backup.')}}
async function importV2(file){if(!file)return;if(file.size>MAX)return toast('O backup excede 20 MB.');let data;try{data=JSON.parse(await file.text())}catch{return toast('Arquivo JSON inválido.')}data=normalizeLegacyBackup(data);const err=validate(data);if(err)return toast(err);if(!confirm('ATENÇÃO\n\nA importação substituirá os dados pessoais atuais, incluindo o estoque.\n\nContinuar?'))return false;data=migrate(data);const d=await open();try{const internal=(await all(d,'settings')).filter(x=>['referenceDataVersion','referenceSeedV230'].includes(x.key));const stores=['catalogs','lists','history','wishlist','trash','settings','inventory'];await tx(d,stores,t=>{for(const s of stores)t.objectStore(s).clear();for(const c of data.catalogs)t.objectStore('catalogs').put(c);for(const l of data.lists)t.objectStore('lists').put(l);for(const h of data.history)t.objectStore('history').put(h);for(const w of data.wishlist)t.objectStore('wishlist').put(w);for(const x of data.trash)t.objectStore('trash').put(x);for(const i of data.inventory||[])t.objectStore('inventory').put(i);for(const [k,v] of Object.entries(cleanSettings(data.settings)))t.objectStore('settings').put({key:k,value:v});for(const x of internal)t.objectStore('settings').put(x)});d.close();toast('Backup restaurado com sucesso.');setTimeout(()=>location.reload(),150);return true}catch(e){try{d.close()}catch{}console.error(e);toast('Erro ao restaurar o backup. Nenhum dado parcial foi aplicado.');return false}}
function bind(){const b=$('exportBtn'),input=$('importInput');if(b&&!b.dataset.v230Backup){b.dataset.v230Backup='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();exportV2()},{capture:true})}if(input&&!input.dataset.v230Backup){input.dataset.v230Backup='1';input.addEventListener('change',e=>{e.stopImmediatePropagation();const f=e.target.files?.[0];if(f)importV2(f);e.target.value=''},{capture:true})}}
function init(){bind();new MutationObserver(bind).observe(document.body,{subtree:true,childList:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.__mlBackupV230={validate,migrate,snapshot,normalizeLegacyBackup};
})();
