(()=>{
'use strict';
const DB='MinhaListaDB',MAX=12000,ID_RE=/^[A-Za-z0-9_-]{36}$/;
const API=String(globalThis.MINHA_LISTA_SHARE_API||'').trim().replace(/\/+$/,'');
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('pt-BR');
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const notify=m=>{const t=document.getElementById('toast');if(t){t.textContent=m;t.classList.add('show');clearTimeout(t._mlt);t._mlt=setTimeout(()=>t.classList.remove('show'),2800)}else alert(m)};
const copy=async text=>{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return}const ta=document.createElement('textarea');ta.value=text;ta.style.cssText='position:fixed;left:-9999px';document.body.appendChild(ta);ta.select();if(!document.execCommand('copy'))throw Error('copy-failed');ta.remove()};
const read=(store,mode='readonly')=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB);r.onerror=()=>reject(r.error||Error('IndexedDB indisponível'));r.onsuccess=()=>{const d=r.result;let t;try{t=d.transaction(store,mode)}catch(e){d.close();reject(e);return}const q=t.objectStore(store).getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>reject(q.error||Error('Falha IndexedDB'));t.oncomplete=()=>d.close();t.onerror=()=>{d.close();reject(t.error||Error('Falha IndexedDB'))}}});
const write=(stores,fn)=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB);r.onerror=()=>reject(r.error||Error('IndexedDB indisponível'));r.onsuccess=()=>{const d=r.result;let t;try{t=d.transaction(stores,'readwrite');fn(t)}catch(e){try{t?.abort()}catch{}d.close();reject(e);return}t.oncomplete=()=>{d.close();resolve()};t.onerror=()=>{d.close();reject(t.error||Error('Falha IndexedDB'))};t.onabort=()=>{d.close();reject(t.error||Error('Transação cancelada'))}}});
function encode(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function decode(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const b=atob(s),bytes=Uint8Array.from(b,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
function validDate(v){if(v==null||v==='')return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return false;const [y,m,d]=String(v).split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d}
async function payload(list){const cats=await read('catalogs'),used=new Set((list.items||[]).map(i=>i.mainItemId).filter(Boolean));return{app:'Minha Lista de Supermercado',format:'shared-list-v3',version:3,list:{...list,items:(list.items||[]).map(i=>({...i,packageQuantity:i.packageQuantity??null,packageUnit:i.packageUnit??null,expiryDate:i.expiryDate??null}))},catalogs:cats.filter(c=>used.has(c.id)).map(c=>({...c}))}}
async function selected(){const s=document.getElementById('shareSelect');return s?.value?(await read('lists')).find(l=>l.id===s.value):null}
async function remote(p){if(!API)throw Error('disabled');const r=await fetch(`${API}/api/share`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p),cache:'no-store'});if(!r.ok)throw Error(`http-${r.status}`);const d=await r.json();if(!d?.url||!ID_RE.test(String(d.id||'')))throw Error('bad-response');return d.url}
function local(p){const u=location.href.split('#')[0]+'#lista='+encode(p);if(u.length>MAX)throw Error('too-large');return u}
async function link(l){const p=await payload(l);if(API){try{return{url:await remote(p),remote:true}}catch(e){console.warn('Compartilhamento remoto indisponível',e)}}return{url:local(p),remote:false}}
function show(lists){const m=document.getElementById('modal'),t=document.getElementById('modalTitle'),b=document.getElementById('modalBody');if(!m||!t||!b)return notify('Compartilhamento indisponível.');const active=lists.filter(l=>!l.archived);if(!active.length)return notify('Crie uma lista primeiro.');b.innerHTML=`<div class="field"><label for="shareSelect">Escolha a lista</label><select id="shareSelect" class="select">${active.map(l=>`<option value="${esc(l.id)}">${esc(l.name||'Lista')}</option>`).join('')}</select></div><div class="subcard" style="margin-top:10px"><strong>🔗 Compartilhar lista</strong><div class="hint">O estoque nunca é incluído. O link local contém apenas a lista e os produtos usados por ela.</div><div class="row stack-mobile" style="margin-top:9px"><button class="btn primary" id="mlCopyLink">🔗 Copiar link</button><button class="btn ghost" id="mlShareLink">📱 Compartilhar</button><button class="btn ghost" id="mlCopyData">📋 Copiar dados</button><button class="btn ghost" id="mlExport">📁 Exportar JSON</button></div></div>`;t.textContent='Compartilhar lista';m.classList.add('show');document.body.style.overflow='hidden';setTimeout(()=>document.getElementById('shareSelect')?.focus(),30);document.getElementById('mlCopyLink').onclick=copyLink;document.getElementById('mlShareLink').onclick=shareLink;document.getElementById('mlCopyData').onclick=copyData;document.getElementById('mlExport').onclick=exportList}
async function copyLink(){const l=await selected();if(!l)return notify('Selecione uma lista.');try{const x=await link(l);await copy(x.url);notify(x.remote?'🔗 Link curto copiado.':'🔗 Link local copiado.')}catch(e){notify(e.message==='too-large'?'Lista grande demais para link. Use Exportar JSON.':'Não foi possível gerar o link.')}}
async function shareLink(){const l=await selected();if(!l)return notify('Selecione uma lista.');try{const x=await link(l);if(typeof navigator.share==='function'){await navigator.share({title:l.name||'Lista de supermercado',text:'Lista de supermercado',url:x.url});return}await copy(x.url);notify(x.remote?'🔗 Link curto copiado.':'🔗 Link local copiado.')}catch(e){if(e.name!=='AbortError')notify('Não foi possível compartilhar.')}}
async function copyData(){const l=await selected();if(!l)return notify('Selecione uma lista.');try{await copy(JSON.stringify(await payload(l),null,2));notify('📋 Dados copiados.')}catch{notify('Não foi possível copiar os dados.')}}
async function exportList(){const l=await selected();if(!l)return notify('Selecione uma lista.');try{const p=await payload(l),u=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='lista-'+(norm(l.name).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'lista')+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);notify('📁 JSON criado.')}catch{notify('Não foi possível exportar a lista.')}}
function validItem(i,map){return i&&typeof i.id==='string'&&i.id.length>=6&&typeof i.mainItemId==='string'&&map.has(i.mainItemId)&&typeof i.done==='boolean'&&(i.quantity==null||Number.isFinite(Number(i.quantity))&&Number(i.quantity)>0&&Number(i.quantity)<=1000000)&&validDate(i.date)&&typeof i.marketName==='string'&&typeof i.comments==='string'&&(i.packageQuantity==null||Number.isFinite(Number(i.packageQuantity))&&Number(i.packageQuantity)>0&&Number(i.packageQuantity)<=1000000)&&validDate(i.expiryDate)}
async function importPayload(p){if(!p||p.app!=='Minha Lista de Supermercado'||!['shared-list-v2','shared-list-v3'].includes(p.format)||![2,3].includes(p.version)||!p.list||!Array.isArray(p.list.items)||!Array.isArray(p.catalogs))throw Error('incompatible');if(!confirm(`Importar a lista "${String(p.list.name||'Lista compartilhada').slice(0,120)}"?\n\nEla será adicionada como uma nova lista. O estoque deste dispositivo não será alterado.`))return false;const cats=await read('catalogs'),byKey=new Map(cats.map(c=>[`${norm(c.name)}|${norm(c.brand)}|${norm(c.unit||'un')}`,c.id])),map=new Map(),newCats=[];for(const c of p.catalogs){if(!c||typeof c.id!=='string'||typeof c.name!=='string'||!c.name.trim())throw Error('invalid-catalog');const key=`${norm(c.name)}|${norm(c.brand)}|${norm(c.unit||'un')}`,existing=byKey.get(key);if(existing)map.set(c.id,existing);else{const nc={id:uid(),name:String(c.name).slice(0,120),brand:String(c.brand||'').slice(0,80),unit:String(c.unit||'un').slice(0,40),category:String(c.category||'Outros').slice(0,80),notes:String(c.notes||'').slice(0,1000),ean:String(c.ean||'').replace(/\D/g,'').slice(0,14)};newCats.push(nc);map.set(c.id,nc.id)}}const items=p.list.items.map(i=>{if(!validItem(i,map))throw Error('invalid-item');return{...i,id:uid(),mainItemId:map.get(i.mainItemId),packageQuantity:i.packageQuantity==null?null:Number(i.packageQuantity),packageUnit:i.packageUnit?String(i.packageUnit).slice(0,40):null,expiryDate:i.expiryDate||null}});const nl={...p.list,id:uid(),name:String(p.list.name||'Lista compartilhada').slice(0,120),createdAt:new Date().toISOString(),archived:false,items};await write(['catalogs','lists'],t=>{for(const c of newCats)t.objectStore('catalogs').put(c);t.objectStore('lists').put(nl)});return true}
async function importRemote(){const sid=new URLSearchParams(location.search).get('shared');if(!sid)return false;history.replaceState(null,'',location.pathname);if(!API)return notify('Compartilhamento remoto não está configurado.'),true;if(!ID_RE.test(sid))return notify('Link remoto inválido.'),true;try{const r=await fetch(`${API}/api/share/${sid}`,{cache:'no-store'});if(!r.ok)throw Error('remote');const p=await r.json();if(await importPayload(p))location.reload()}catch(e){console.error(e);notify('Não foi possível obter a lista compartilhada.')}return true}
async function importHash(){if(!location.hash.startsWith('#lista='))return;const raw=location.hash.slice(7);history.replaceState(null,'',location.pathname+location.search);let p;try{if(raw.length>MAX)throw Error();p=decode(raw)}catch{return notify('Link inválido ou corrompido.')}try{const ok=await importPayload(p);if(ok)location.reload()}catch(e){console.error(e);notify(e.message==='incompatible'?'Link incompatível.':'Não foi possível importar a lista. Nenhum dado foi alterado.')}}
function bind(){const b=document.getElementById('shareListBtn');if(!b||b.dataset.mlShareFixed)return;b.dataset.mlShareFixed='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();read('lists').then(show).catch(()=>notify('Não foi possível abrir o compartilhamento.'))},{capture:true})}
function init(){bind();setTimeout(bind,500);setTimeout(async()=>{if(!(await importRemote()))await importHash()},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();