(()=>{
'use strict';
const DB='MinhaListaDB', MAX=12000, SHARE_ID_RE=/^[A-Za-z0-9_-]{36}$/;
const API=String(globalThis.MINHA_LISTA_SHARE_API||'').trim().replace(/\/+$/,'');
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('pt-BR');
const id=()=>globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const notify=m=>{const t=document.getElementById('toast');if(t){t.textContent=m;t.classList.add('show');clearTimeout(t._mlt);t._mlt=setTimeout(()=>t.classList.remove('show'),2800)}else alert(m)};
const copy=async text=>{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true}const ta=document.createElement('textarea');ta.value=text;ta.style.cssText='position:fixed;left:-9999px';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();if(!ok)throw Error('copy failed');return true};
const readStore=(store,mode='readonly')=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB);r.onerror=()=>reject(r.error||Error('IndexedDB indisponível'));r.onsuccess=()=>{const d=r.result;let tx;try{tx=d.transaction(store,mode)}catch(e){d.close();reject(e);return}const q=tx.objectStore(store).getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>reject(q.error||Error('Falha na leitura'));tx.oncomplete=()=>d.close();tx.onerror=()=>{d.close();reject(tx.error||Error('Falha IndexedDB'))}}});
const write=(stores,fn)=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB);r.onerror=()=>reject(r.error||Error('IndexedDB indisponível'));r.onsuccess=()=>{const d=r.result;let tx;try{tx=d.transaction(stores,'readwrite');fn(tx)}catch(e){try{tx?.abort()}catch{}d.close();reject(e);return}tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{d.close();reject(tx.error||Error('Falha IndexedDB'))};tx.onabort=()=>{d.close();reject(tx.error||Error('Transação cancelada'))}}});
function encode(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function decode(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const b=atob(s),bytes=Uint8Array.from(b,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
async function payload(list){const cats=await readStore('catalogs');const used=new Set((list.items||[]).map(i=>i.mainItemId).filter(Boolean));return {app:'Minha Lista de Supermercado',format:'shared-list-v2',version:2,list:{...list,items:(list.items||[]).map(i=>({...i}))},catalogs:cats.filter(c=>used.has(c.id)).map(c=>({...c}))}}
async function selectedList(){const s=document.getElementById('shareSelect');if(!s?.value)return null;return (await readStore('lists')).find(l=>l.id===s.value)||null}
async function remoteShare(p){if(!API)throw Error('share-api-disabled');const r=await fetch(`${API}/api/share`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p),cache:'no-store'});if(!r.ok)throw Error('share-http-'+r.status);const data=await r.json();if(!data?.url||typeof data.url!=='string'||!SHARE_ID_RE.test(String(data.id||'')))throw Error('share-response');return data.url}
function localLink(p){const text=location.href.split('#')[0]+'#lista='+encode(p);if(text.length>MAX)throw Error('local-link-too-large');return text}
async function makeShareLink(l){const p=await payload(l);if(API){try{return{url:await remoteShare(p),remote:true}}catch(e){console.warn('Compartilhamento remoto indisponível:',e)}}return{url:localLink(p),remote:false}}
async function copyLink(){const l=await selectedList();if(!l)return notify('Selecione uma lista.');try{const x=await makeShareLink(l);await copy(x.url);notify(x.remote?'🔗 Link curto copiado.':'🔗 Link local copiado.')}catch(e){notify(e.message==='local-link-too-large'?'Lista grande demais para link. Use Exportar lista.':'Não foi possível gerar o link.')}}
async function shareLink(){const l=await selectedList();if(!l)return notify('Selecione uma lista.');try{const x=await makeShareLink(l);if(navigator.share)await navigator.share({title:l.name||'Lista de supermercado',text:'Lista de supermercado',url:x.url});else await copy(x.url);if(!navigator.share)notify(x.remote?'🔗 Link curto copiado.':'🔗 Link local copiado.')}catch(e){if(e.name!=='AbortError')notify(e.message==='local-link-too-large'?'Link grande demais. Use Exportar lista.':'Não foi possível compartilhar.')}}
async function copyData(){const l=await selectedList();if(!l)return notify('Selecione uma lista.');try{await copy(JSON.stringify(await payload(l),null,2));notify('📋 Dados copiados.')}catch{notify('Não foi possível copiar os dados.')}}
async function exportList(){const l=await selectedList();if(!l)return notify('Selecione uma lista.');const p=await payload(l),u=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='lista-'+norm(l.name).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);notify('📁 Lista exportada.')}
function shareTools(){const modal=document.getElementById('modal'),body=document.getElementById('modalBody'),select=document.getElementById('shareSelect');if(!modal||!body||!select||body.querySelector('#mlShareTools'))return;const box=document.createElement('div');box.id='mlShareTools';box.className='subcard';box.style.marginTop='10px';box.innerHTML='<strong>🔗 Compartilhamento</strong><div class="hint">Com servidor configurado, gera um link curto temporário. Sem servidor ou offline, usa um link local ou arquivo.</div><div class="row stack-mobile" style="margin-top:9px"><button class="btn primary" type="button" id="mlCopyLink">🔗 Copiar link</button><button class="btn ghost" type="button" id="mlShareLink">📱 Compartilhar</button><button class="btn ghost" type="button" id="mlCopyData">📋 Copiar dados</button><button class="btn ghost" type="button" id="mlExport">📁 Exportar lista</button></div>';(body.querySelector('#doShare')?.parentElement||body).appendChild(box);box.querySelector('#mlCopyLink').onclick=copyLink;box.querySelector('#mlShareLink').onclick=shareLink;box.querySelector('#mlCopyData').onclick=copyData;box.querySelector('#mlExport').onclick=exportList}
function searchFix(){const input=document.getElementById('listItemSearch');if(!input||input.dataset.mlFixed)return;input.dataset.mlFixed='1';input.addEventListener('input',e=>{e.stopImmediatePropagation();const q=norm(input.value);document.querySelectorAll('#listItems .item').forEach(x=>{x.style.display=!q||norm(x.textContent).includes(q)?'':'none'})},{capture:true});}
async function importPayload(p){if(!p||p.app!=='Minha Lista de Supermercado'||p.format!=='shared-list-v2'||p.version!==2||!p.list||!Array.isArray(p.list.items)||!Array.isArray(p.catalogs))throw Error('incompatible');if(!confirm(`Importar a lista "${String(p.list.name||'Lista compartilhada').slice(0,120)}"?\n\nEla será adicionada como uma nova lista.`))return false;const cats=await readStore('catalogs'),byKey=new Map(cats.map(c=>[`${norm(c.name)}|${norm(c.brand)}|${norm(c.unit||'un')}`,c.id])),map=new Map(),newCats=[];for(const c of p.catalogs){if(!c||typeof c.name!=='string'||!c.name.trim())throw Error('invalid-catalog');const key=`${norm(c.name)}|${norm(c.brand)}|${norm(c.unit||'un')}`,existing=byKey.get(key);if(existing)map.set(c.id,existing);else{const nc={...c,id:id(),name:String(c.name).slice(0,120),brand:String(c.brand||'').slice(0,120),unit:String(c.unit||'un').slice(0,60),category:String(c.category||'Outros').slice(0,80),notes:String(c.notes||'').slice(0,2000),ean:String(c.ean||'').replace(/\D/g,'').slice(0,14)};newCats.push(nc);map.set(c.id,nc.id)}}const items=p.list.items.map(i=>{const mainItemId=map.get(i.mainItemId);if(!mainItemId)throw Error('invalid-reference');return{...i,id:id(),mainItemId}});const nl={...p.list,id:id(),name:String(p.list.name||'Lista compartilhada').slice(0,120),createdAt:new Date().toISOString(),archived:false,items};await write(['catalogs','lists'],tx=>{for(const c of newCats)tx.objectStore('catalogs').put(c);tx.objectStore('lists').put(nl)});return true}
async function importRemote(){const sp=new URLSearchParams(location.search),sid=sp.get('shared');if(!sid)return false;history.replaceState(null,'',location.pathname);if(!SHARE_ID_RE.test(sid))return notify('Link de compartilhamento inválido.'),true;if(!API)return notify('Compartilhamento remoto ainda não está configurado nesta versão.'),true;try{const r=await fetch(`${API}/api/share/${sid}`,{cache:'no-store'});if(!r.ok)throw Error(r.status===404?'not-found':'remote-failed');const p=await r.json();if(await importPayload(p))location.reload()}catch(e){console.error(e);notify(e.message==='not-found'?'Compartilhamento expirado ou não encontrado.':'Não foi possível obter a lista compartilhada.')}return true}
async function importHash(){if(!location.hash.startsWith('#lista='))return;const raw=location.hash.slice(7);history.replaceState(null,'',location.pathname+location.search);let p;try{if(raw.length>MAX)throw Error();p=decode(raw)}catch{return notify('Link inválido ou corrompido.')}try{await importPayload(p)}catch(e){console.error(e);notify(e.message==='incompatible'?'Link incompatível.':'Não foi possível importar a lista. Nenhum dado foi alterado.')}location.reload()}
function init(){searchFix();const modal=document.getElementById('modal');if(modal)new MutationObserver(()=>{if(modal.classList.contains('show'))shareTools();searchFix()}).observe(modal,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});setTimeout(async()=>{if(!(await importRemote()))await importHash()},200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
