(()=>{
'use strict';
const DB='MinhaListaDB',MAX=20*1024*1024;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const t=$('toast');if(t){t.textContent=m;t.classList.add('show');clearTimeout(t._v230);t._v230=setTimeout(()=>t.classList.remove('show'),2800)}else alert(m)};
const open=()=>new Promise((res,rej)=>{const r=indexedDB.open(DB);r.onerror=()=>rej(r.error||Error('IndexedDB indisponível'));r.onsuccess=()=>res(r.result)});
const all=(d,s)=>new Promise((res,rej)=>{const r=d.transaction(s,'readonly').objectStore(s).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});
const tx=(d,stores,fn)=>new Promise((res,rej)=>{let t;try{t=d.transaction(stores,'readwrite');fn(t)}catch(e){try{t?.abort()}catch{}rej(e);return}t.oncomplete=res;t.onerror=()=>rej(t.error||Error('Falha IndexedDB'));t.onabort=()=>rej(t.error||Error('Transação cancelada'))});
const download=(name,text)=>{const u=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)};
function cleanSettings(s){return Object.fromEntries(Object.entries(s||{}).filter(([k])=>!['referenceDataVersion','referenceSeedV230'].includes(k)))}
async function snapshot(){const d=await open();try{const [catalogs,lists,history,wishlist,trash,settings,inventory]=await Promise.all(['catalogs','lists','history','wishlist','trash','settings','inventory'].map(s=>all(d,s)));return{app:'Minha Lista de Supermercado',backupFormatVersion:2,schemaVersion:6,exportedAt:new Date().toISOString(),catalogs,lists,history,wishlist,trash,inventory,settings:cleanSettings(Object.fromEntries(settings.map(x=>[x.key,x.value])))}}finally{d.close()}}
function validDate(v){if(v==null||v==='')return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return false;const [y,m,day]=String(v).split('-').map(Number),x=new Date(Date.UTC(y,m-1,day));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===day}
function id(v){return typeof v==='string'&&v.length>=6&&v.length<=100}
function num(v,max=1000000,positive=false){if(v==null||v==='')return null;const n=typeof v==='number'?v:Number(String(v).replace(',','.'));return Number.isFinite(n)&&n>=0&&n<=max&&(!positive||n>0)?n:null}
function validate(data){if(!data||data.app!=='Minha Lista de Supermercado')return 'Arquivo incompatível.';if(![1,2].includes(data.backupFormatVersion))return 'Versão de backup não suportada.';for(const k of ['catalogs','lists','history','wishlist','trash'])if(!Array.isArray(data[k]))return `Campo inválido: ${k}.`;if(!data.settings||typeof data.settings!=='object'||Array.isArray(data.settings))return 'Configurações inválidas.';if(data.backupFormatVersion===2&&!Array.isArray(data.inventory))return 'Estoque inválido.';if(JSON.stringify(data).length>MAX)return 'O backup excede 20 MB.';const cats=new Set();for(const c of data.catalogs){if(!c||!id(c.id)||typeof c.name!=='string'||!c.name.trim()||c.name.length>120)return 'Catálogo inválido.';if(cats.has(c.id))return 'Catálogo duplicado.';cats.add(c.id)}const trashCats=new Set(data.trash.filter(t=>t?.type==='catalog'&&t.data?.id).map(t=>t.data.id));const allCats=new Set([...cats,...trashCats]);const lists=new Set();for(const l of data.lists){if(!l||!id(l.id)||typeof l.name!=='string'||!l.name.trim()||l.name.length>120||!Array.isArray(l.items)||!validDate(l.date))return 'Lista inválida.';if(lists.has(l.id))return 'Lista duplicada.';lists.add(l.id);for(const i of l.items){if(!i||!id(i.id)||!id(i.mainItemId)||!allCats.has(i.mainItemId)||typeof i.done!=='boolean'||num(i.quantity,1000000,true)===null&&i.quantity!=null||num(i.value,1000000000)===null&&i.value!=null||!validDate(i.date)||typeof i.marketName!=='string'||typeof i.comments!=='string')return 'Item de lista inválido.'}}
for(const h of data.history){if(!h||!id(h.id)||h.mainItemId&&!allCats.has(h.mainItemId)||typeof h.itemName!=='string'||num(h.value,1000000000)===null||!validDate(h.date))return 'Histórico inválido.'}
for(const w of data.wishlist)if(!w||!id(w.id)||typeof w.name!=='string'||!w.name.trim())return 'Lista de desejos inválida.';
for(const t of data.trash)if(!t||!id(t.id)||!['catalog','list'].includes(t.type)||!t.data)return 'Lixeira inválida.';
if(data.backupFormatVersion===2)for(const x of data.inventory){if(!x||!id(x.id)||!id(x.mainItemId)||!allCats.has(x.mainItemId)||num(x.quantity,1000000,true)===null||num(x.packageQuantity,1000000,true)===null||!validDate(x.expiryDate)||!validDate(x.entryDate)||num(x.minQuantity,1000000)===null)return 'Registro de estoque inválido.'}
return null}
function migrate(data){if(data.backupFormatVersion===2)return data;return{...data,backupFormatVersion:2,schemaVersion:6,inventory:[]}}
async function exportV2(){try{const data=await snapshot();download(`minha-lista-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2));toast('Backup V2 exportado com estoque.')}catch(e){console.error(e);toast('Não foi possível exportar o backup.')}}
async function importV2(file){if(!file)return;if(file.size>MAX){toast('O backup excede 20 MB.');return}let data;try{data=JSON.parse(await file.text())}catch{toast('Arquivo JSON inválido.');return}const err=validate(data);if(err){toast(err);return}if(!confirm('ATENÇÃO\n\nA importação substituirá listas, produtos, histórico, desejos, lixeira, configurações e estoque atuais.\n\nContinuar?'))return;data=migrate(data);const d=await open();try{const stores=['catalogs','lists','history','wishlist','trash','settings','inventory'];await tx(d,stores,t=>{for(const s of stores)t.objectStore(s).clear();for(const c of data.catalogs)t.objectStore('catalogs').put(c);for(const l of data.lists)t.objectStore('lists').put(l);for(const h of data.history)t.objectStore('history').put(h);for(const w of data.wishlist)t.objectStore('wishlist').put(w);for(const x of data.trash)t.objectStore('trash').put(x);for(const i of data.inventory||[])t.objectStore('inventory').put(i);for(const [k,v] of Object.entries(cleanSettings(data.settings)))t.objectStore('settings').put({key:k,value:v})});d.close();toast('Backup restaurado com sucesso.');setTimeout(()=>location.reload(),150)}catch(e){d.close();console.error(e);toast('Erro ao restaurar backup. Nenhum dado foi parcialmente aplicado.')}}
function bind(){const b=$('exportBtn'),input=$('importInput');if(b&&!b.dataset.v230){b.dataset.v230='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();exportV2()},{capture:true})}if(input&&!input.dataset.v230){input.dataset.v230='1';input.addEventListener('change',e=>{e.stopImmediatePropagation();const f=e.target.files?.[0];if(f)importV2(f);e.target.value=''},{capture:true})}}
function inject(){document.querySelectorAll('.sub,.privacy-version').forEach(x=>{if(x.textContent.includes('v2.2.2'))x.textContent=x.textContent.replace(/v2\.2\.2/g,'v2.3.0')});const s=$('settingsView');if(s&&!s.querySelector('[data-v230-backup-note]')){const p=document.createElement('div');p.className='hint';p.dataset.v230BackupNote='1';p.textContent='V2.3.0: backups incluem o estoque; banco de referência permanece separado e não é exportado.';const panel=s.querySelector('.panel');panel?.appendChild(p)}if(!$('inventoryView'))document.querySelector('.nav-inner')?.querySelector('[data-view="inventoryView"]')?.click()}
function init(){bind();inject();new MutationObserver(()=>{bind();inject()}).observe(document.body,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.__mlV230={open,all,tx,toast,esc};
})();