const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const source=fs.readFileSync('db-migrations-v230.js','utf8');
const context={window:{},Object,Array,Number,String,TypeError,Error};
vm.createContext(context);
vm.runInContext(source,context);
const api=context.window.__mlDbMigrationsV230;
assert(api,'contrato de migrações não carregado');
assert.strictEqual(api.DB_NAME,'MinhaListaDB');
assert.strictEqual(api.LATEST,6);
assert.deepStrictEqual(Array.from(api.MIGRATIONS[1]),['catalogs','lists','history','settings']);
assert.deepStrictEqual(Array.from(api.MIGRATIONS[2]),['wishlist']);
assert.deepStrictEqual(Array.from(api.MIGRATIONS[3]),['trash']);
assert.deepStrictEqual(Array.from(api.MIGRATIONS[4]),['referenceProducts','referenceMarkets']);
assert.deepStrictEqual(Array.from(api.MIGRATIONS[5]),[]);
assert.deepStrictEqual(Array.from(api.MIGRATIONS[6]),['inventory']);
assert.strictEqual(api.keyPath('settings'),'key');
assert.strictEqual(api.keyPath('inventory'),'id');
assert.deepStrictEqual(Array.from(api.plan(0,6)),['catalogs','lists','history','settings','wishlist','trash','referenceProducts','referenceMarkets','inventory']);
assert.deepStrictEqual(Array.from(api.plan(5,6)),['inventory']);
assert.throws(()=>api.plan(7,6),/oldVersion/);
assert.throws(()=>api.plan(-1,6),/oldVersion/);
assert.throws(()=>api.plan(0,0),/newVersion/);
console.log('V2.3.0 migration contract tests: OK');
